"""Render structured workflow results as user replies with switchable tones."""

from typing import Literal

from .workflow_constants import FALCON_SCOPE_MESSAGE, SAFE_ERROR_MESSAGE


ToneName = Literal["direct", "warm", "concise"]


class ResponseRenderer:
    """Centrally manage Falcon reply templates to ensure tone changes do not modify business state."""

    def __init__(self, tone: ToneName = "warm") -> None:
        """Select one of three local debugging tones: direct, gentle-professional, or minimal."""

        self.tone = tone

    def out_of_scope(self) -> str:
        """Return the fixed scope notice that product requirements state must not be rewritten."""

        return FALCON_SCOPE_MESSAGE

    def error(self) -> str:
        """Return a safe error notice that does not leak internal exceptions."""

        if self.tone == "concise":
            return "I can't process that right now. Please try again later."
        if self.tone == "direct":
            return SAFE_ERROR_MESSAGE
        return (
            "Sorry, I ran into a problem while processing your requirements. "
            "Please try again later, and I'll continue helping you refine your housing needs."
        )

    def cancelled(self) -> str:
        """Return the notice for when the user cancels the current home-finding flow."""

        if self.tone == "concise":
            return "This housing request has been cancelled."
        if self.tone == "direct":
            return "Your housing request has been cancelled."
        return "Your housing request has been cancelled. Feel free to return whenever you need help."

    def clarification(self, questions: list[dict[str, str]]) -> str:
        """Render structured questions as a clarification reply of no more than three items."""

        body = "\n".join(f"{index}. {item['text']}" for index, item in enumerate(questions, 1))
        if self.tone == "concise":
            return body
        if self.tone == "direct":
            return f"Please provide the following information:\n{body}"
        return (
            "I've noted your requirements so far. To narrow down the search more accurately, "
            f"please provide:\n{body}"
        )

    def confirmation(self, summary: str) -> str:
        """Render a requirements confirmation reply strictly consistent with the structured profile."""

        if self.tone == "concise":
            return f"Requirements: {summary}\nIs this correct?"
        if self.tone == "direct":
            return f"I understand your requirements as follows: {summary}\nIs this correct?"
        return (
            f"Here is my understanding of your requirements:\n{summary}\n"
            "Please confirm whether this is correct, or tell me what you would like to change."
        )

    def ready_for_b(self) -> str:
        """Return the notice for when the confirmed profile is ready to hand off to B."""

        if self.tone == "concise":
            return "Requirements confirmed."
        if self.tone == "direct":
            return "Requirements confirmed and ready for the listing retrieval module."
        return "Your requirements are confirmed. I'll continue searching for suitable listings."

    def search_failed(self, issues: list[dict[str, str]] | None = None) -> str:
        """Provide an explanation that does not leak internal details when the search cannot continue."""

        # Internal diagnostics may come from multilingual sources; user-facing error explanations are uniformly in English and do not leak the original exception.
        first_issue = (issues or [{}])[0] if issues else {}
        code = first_issue.get("code")
        source = first_issue.get("source")
        detail = {
            "TIMEOUT": "The search timed out. Please retry or narrow your search.",
            "SOURCE_UNAVAILABLE": "The listing source is unavailable. Please try again later.",
            "RATE_LIMITED": "The listing source is busy. Please try again later.",
        }.get(code)
        if code == "MODEL_UNAVAILABLE":
            detail = (
                "The search planning service is unavailable. Please try again later."
                if source == "model"
                else "The recommendation service is unavailable. Please try again later."
            )
        if self.tone == "concise":
            return detail or "Search could not be completed."
        if detail:
            return f"I could not complete the listing search: {detail}"
        return "I could not complete the listing search. Please try again or adjust your requirements."

    def recommendation(self, text: str) -> str:
        """When publishing recommendations, reuse the summary and items already generated by the model."""

        return text.strip() or "Here are the listings I recommend."

    def run_finished(self, reason: str | None = None) -> str:
        """Closing explanation for when the search run ends but there are no new recommendations."""

        if reason == "user_declined":
            return "Understood. I'll keep your original requirements and stop this search."
        if reason == "cancelled":
            return self.cancelled()
        if reason == "budget_exhausted":
            return (
                "I completed the available search attempts, but did not find a listing "
                "that satisfies all confirmed requirements. Tell me which requirement "
                "you would like to adjust, and I can search again."
            )
        if reason == "verification_pending":
            return (
                "The listings found have missing information needed to verify your requirements, "
                "so I can't recommend them as confirmed matches. I haven't requested another search. "
                "You can adjust your requirements or ask me to search again."
            )
        if self.tone == "concise":
            return "This search has ended."
        return "This search has ended. Tell me if you would like to change your requirements and search again."
