"""Verify that the confirmation request generated by A can complete an offline handoff through B's public entry point."""

import asyncio
from datetime import datetime, timedelta, timezone
import unittest
from unittest.mock import patch

from property_agent.search.api import fulfill_requirements
from property_agent.search.fulfillment import FulfillmentService
from property_agent.requirements.workflow import build_requirement_request


class RecordingPlanner:
    """Record A's request and return a valid search plan that does not depend on an external model."""

    def __init__(self) -> None:
        self.request = None

    async def build_for_request(self, request, query, previous_attempts, directive, *, ctx):
        """Simulate B's internal planning stage while retaining the public request for assertions."""

        self.request = request
        return {
            "status": "success",
            "data": {
                "plan_id": "plan-a-b-integration",
                "profile_version": request["profile_version"],
                "attempt_id": "attempt-a-b-integration",
                "intent": request["intent"],
                "required_filters": {
                    "currency": "SGD",
                    "max_price": 3500,
                    "price_period": "month",
                    "rental_scope": "whole_unit",
                    "locations": ["TAMPINES"],
                    "min_bedrooms": 2,
                },
                "queries": [{
                    "query_id": "query-tampines",
                    "source": "propertyguru",
                    "text": "Tampines",
                    "cursor": None,
                }],
                "page_limit": 1,
                "candidate_limit": 3,
                "source_mode": ctx["source_mode"],
                "reason": "A/B contract integration smoke test",
            },
            "issues": [],
            "meta": {
                "trace_id": ctx["trace_id"],
                "call_id": ctx["call_id"],
                "duration_ms": 0,
            },
        }


class EmptySearchService:
    """Return a complete empty result, used only to verify the communication contract without fabricating listings."""

    async def search_for_request(self, plan, request, *, ctx):
        """Simulate the end of B's search, retaining the real Result[SearchResult] wrapper."""

        return {
            "status": "success",
            "data": {
                "plan_id": plan["plan_id"],
                "profile_version": request["profile_version"],
                "items": [],
                "coverage": {
                    "queried_sources": ["propertyguru"],
                    "failed_sources": [],
                    "queries_completed": True,
                    "has_more": False,
                    "next_pages": [],
                    "truncated": False,
                    "applied_filters": [],
                    "unsupported_filters": [],
                },
            },
            "issues": [],
            "meta": {
                "trace_id": ctx["trace_id"],
                "call_id": ctx["call_id"],
                "duration_ms": 0,
            },
        }


def confirmed_profile() -> dict:
    """Construct a session profile owned by A, already confirmed, and ready to be handed to B."""

    message = "Whole-unit rental, monthly rent at most 3500 SGD, Tampines, at least two bedrooms."
    source = {
        "message_id": "msg-a-b-001",
        "text": message,
        "start": 0,
        "end": len(message),
    }
    timestamp = "2026-09-21T12:00:00+08:00"
    constraints = [
        ("transaction_type", "eq", "rent"),
        ("price.currency", "eq", "SGD"),
        ("price.amount", "lte", 3500),
        ("price.period", "eq", "month"),
        ("attributes.listing_scope", "eq", "whole_unit"),
        ("bedrooms", "gte", 2),
    ]
    return {
        "profile_id": "profile-a-b-001",
        "user_id": "user-a-b-001",
        "conversation_id": "conversation-a-b-001",
        "version": 1,
        "confirmed_version": 1,
        "status": "confirmed",
        "intent": "rent",
        "user_context": [],
        "listing_constraints": [{
            "constraint_id": f"constraint:{field}",
            "field_path": field,
            "operator": operator,
            "value": value,
            "strength": "hard",
            "priority": "high",
            "source": source,
        } for field, operator, value in constraints],
        "derived_data_requirements": [{
            "requirement_id": "derived:residential-area:tampines",
            "category": "accessibility",
            "target": "Tampines",
            "metric": "residential_area",
            "operator": "eq",
            "value": "in",
            "unit": None,
            "strength": "hard",
            "priority": "high",
            "source": source,
        }],
        "open_data_requirements": [],
        "unresolved": [],
        "field_sources": {"intent": "msg-a-b-001"},
        "created_at": timestamp,
        "updated_at": timestamp,
        "last_user_message_at": timestamp,
        "confirmed_at": timestamp,
    }


class ABCommunicationTests(unittest.TestCase):
    """Cover the public boundary from A's request builder to B's fulfillment response."""

    def test_confirmed_a_request_reaches_b_public_entry(self) -> None:
        """A's actual request should be received by B, retaining the version, session, and trace identifiers."""

        handoff = build_requirement_request({"profile": confirmed_profile()})
        request = handoff["requirement_request"]
        planner = RecordingPlanner()
        service = FulfillmentService(
            planner=planner,
            search_service=EmptySearchService(),
        )
        ctx = {
            "user_id": "user-a-b-001",
            "run_id": "run-a-b-001",
            "conversation_id": request["conversation_id"],
            "attempt_id": None,
            "trace_id": "trace-a-b-001",
            "call_id": "call-a-b-001",
            "deadline_at": (datetime.now(timezone.utc) + timedelta(minutes=1)).isoformat(),
            "source_mode": "mock",
        }

        with patch("property_agent.search.api.create_live_fulfillment_service", return_value=service):
            result = asyncio.run(fulfill_requirements(request, ctx=ctx))

        self.assertEqual(handoff["status"], "ready_for_b")
        self.assertEqual(planner.request, request)
        self.assertEqual(result["status"], "success")
        self.assertEqual(result["data"]["status"], "completed")
        self.assertEqual(result["data"]["request_id"], request["request_id"])
        self.assertEqual(result["data"]["profile_version"], request["profile_version"])
        self.assertEqual(result["meta"]["trace_id"], ctx["trace_id"])
        self.assertEqual(result["meta"]["call_id"], ctx["call_id"])


if __name__ == "__main__":
    unittest.main()
