"""Falcon user reply templates and tone switching tests."""

import unittest

from property_agent.requirements import FALCON_SCOPE_MESSAGE, ResponseRenderer


class ResponseRendererTests(unittest.TestCase):
    """Verify that tone changes do not rewrite fixed-scope prompts and structured facts."""

    def test_planner_failure_is_not_described_as_recommendation_failure(self) -> None:
        rendered = ResponseRenderer("warm").search_failed(
            [{"code": "MODEL_UNAVAILABLE", "source": "model", "message": "hidden"}]
        )

        self.assertIn("search planning service", rendered)
        self.assertNotIn("recommendation service", rendered)

    def test_scope_message_is_identical_for_every_tone(self) -> None:
        """Product-specified English scope prompts must not be rewritten with tone."""

        for tone in ("warm", "direct", "concise"):
            self.assertEqual(ResponseRenderer(tone).out_of_scope(), FALCON_SCOPE_MESSAGE)

    def test_confirmation_preserves_summary_for_every_tone(self) -> None:
        """All tones must preserve verbatim the confirmation summary generated by the profile."""

        summary = "Rent; Monthly budget up to SGD 3000; Preferred location: near Clementi"
        for tone in ("warm", "direct", "concise"):
            self.assertIn(summary, ResponseRenderer(tone).confirmation(summary))

    def test_clarification_preserves_every_question(self) -> None:
        """Gentle templates must not remove the completeness node selection question."""

        questions = [
            {"field": "budget", "text": "What is your budget?"},
            {"field": "scope", "text": "Would you prefer a whole unit or a private room?"},
        ]
        rendered = ResponseRenderer("warm").clarification(questions)
        self.assertIn("What is your budget?", rendered)
        self.assertIn("Would you prefer a whole unit or a private room?", rendered)

    def test_exhausted_search_budget_is_reported_as_no_match(self) -> None:
        rendered = ResponseRenderer("warm").run_finished("budget_exhausted")
        self.assertIn("completed the available search attempts", rendered)
        self.assertNotIn("could not complete", rendered)


if __name__ == "__main__":
    unittest.main()
