"""Four fixed A→B requests: call the public entry point and print the raw return."""

import asyncio
from datetime import datetime, timedelta, timezone
import json

from property_agent.search.api import fulfill_requirements
from property_agent.contracts import RequirementRequest


request_1: RequirementRequest = {
    'request_id': 'request-tampines_condo_rent',
    'schema_version': '0.3-draft',
    'conversation_id': 'thread-tampines_condo_rent',
    'profile_id': 'profile-tampines_condo_rent',
    'profile_version': 1,
    'intent': 'rent',
    'user_context': [],
    'listing_constraints': [
        {
            'constraint_id': 'tampines_condo_rent-c1',
            'field_path': 'transaction_type',
            'operator': 'eq',
            'value': 'rent',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
        {
            'constraint_id': 'tampines_condo_rent-c2',
            'field_path': 'price.amount',
            'operator': 'lte',
            'value': 3800,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
        {
            'constraint_id': 'tampines_condo_rent-c3',
            'field_path': 'price.currency',
            'operator': 'eq',
            'value': 'SGD',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
        {
            'constraint_id': 'tampines_condo_rent-c4',
            'field_path': 'price.period',
            'operator': 'eq',
            'value': 'month',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
        {
            'constraint_id': 'tampines_condo_rent-c5',
            'field_path': 'attributes.listing_scope',
            'operator': 'eq',
            'value': 'whole_unit',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
        {
            'constraint_id': 'tampines_condo_rent-c6',
            'field_path': 'attributes.property_type',
            'operator': 'eq',
            'value': 'condo',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
        {
            'constraint_id': 'tampines_condo_rent-c7',
            'field_path': 'bedrooms',
            'operator': 'gte',
            'value': 2,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
        {
            'constraint_id': 'tampines_condo_rent-c8',
            'field_path': 'attributes.furnishing',
            'operator': 'eq',
            'value': 'fully',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
    ],
    'derived_data_requirements': [
        {
            'requirement_id': 'tampines_condo_rent-area',
            'category': 'accessibility',
            'target': 'Tampines',
            'metric': 'residential_area',
            'operator': 'eq',
            'value': True,
            'unit': None,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-tampines_condo_rent',
                'text': 'I want to rent an entire condominium in Tampines, with monthly rent not exceeding SGD 3800, at least two bedrooms, and fully furnished.',
                'start': 0,
                'end': 55,
            },
        },
    ],
    'open_data_requirements': [],
    'unresolved_fields': [],
    'confirmed_at': '2026-09-20T00:00:00+00:00',
}


request_2: RequirementRequest = {
    'request_id': 'request-clementi_common_room',
    'schema_version': '0.3-draft',
    'conversation_id': 'thread-clementi_common_room',
    'profile_id': 'profile-clementi_common_room',
    'profile_version': 1,
    'intent': 'rent',
    'user_context': [],
    'listing_constraints': [
        {
            'constraint_id': 'clementi_common_room-c1',
            'field_path': 'transaction_type',
            'operator': 'eq',
            'value': 'rent',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c2',
            'field_path': 'price.amount',
            'operator': 'lte',
            'value': 1300,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c3',
            'field_path': 'price.currency',
            'operator': 'eq',
            'value': 'SGD',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c4',
            'field_path': 'price.period',
            'operator': 'eq',
            'value': 'month',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c5',
            'field_path': 'attributes.listing_scope',
            'operator': 'eq',
            'value': 'room',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c6',
            'field_path': 'attributes.property_type',
            'operator': 'eq',
            'value': 'hdb',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c7',
            'field_path': 'attributes.room_type',
            'operator': 'eq',
            'value': 'common',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c8',
            'field_path': 'attributes.utilities_included',
            'operator': 'eq',
            'value': True,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'clementi_common_room-c9',
            'field_path': 'attributes.wifi_included',
            'operator': 'eq',
            'value': True,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
    ],
    'derived_data_requirements': [
        {
            'requirement_id': 'clementi_common_room-area',
            'category': 'accessibility',
            'target': 'Clementi',
            'metric': 'residential_area',
            'operator': 'eq',
            'value': True,
            'unit': None,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-clementi_common_room',
                'text': 'I want to rent a common room in an HDB flat in Clementi, not the whole unit, with monthly rent not exceeding SGD 1300, and utilities and Wi-Fi must be included.',
                'start': 0,
                'end': 58,
            },
        },
    ],
    'open_data_requirements': [],
    'unresolved_fields': [],
    'confirmed_at': '2026-09-20T00:00:00+00:00',
}


request_3: RequirementRequest = {
    'request_id': 'request-punggol_family_rent',
    'schema_version': '0.3-draft',
    'conversation_id': 'thread-punggol_family_rent',
    'profile_id': 'profile-punggol_family_rent',
    'profile_version': 1,
    'intent': 'rent',
    'user_context': [],
    'listing_constraints': [
        {
            'constraint_id': 'punggol_family_rent-c1',
            'field_path': 'transaction_type',
            'operator': 'eq',
            'value': 'rent',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c2',
            'field_path': 'price.amount',
            'operator': 'lte',
            'value': 4200,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c3',
            'field_path': 'price.currency',
            'operator': 'eq',
            'value': 'SGD',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c4',
            'field_path': 'price.period',
            'operator': 'eq',
            'value': 'month',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c5',
            'field_path': 'attributes.listing_scope',
            'operator': 'eq',
            'value': 'whole_unit',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c6',
            'field_path': 'attributes.property_type',
            'operator': 'eq',
            'value': 'hdb',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c7',
            'field_path': 'bedrooms',
            'operator': 'gte',
            'value': 3,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c8',
            'field_path': 'attributes.bathrooms',
            'operator': 'gte',
            'value': 2,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
        {
            'constraint_id': 'punggol_family_rent-c9',
            'field_path': 'attributes.area_sqft',
            'operator': 'gte',
            'value': 1000,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
    ],
    'derived_data_requirements': [
        {
            'requirement_id': 'punggol_family_rent-area',
            'category': 'accessibility',
            'target': 'Punggol',
            'metric': 'residential_area',
            'operator': 'eq',
            'value': True,
            'unit': None,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-punggol_family_rent',
                'text': 'I want to rent an entire HDB flat in Punggol, with monthly rent not exceeding SGD 4200, at least three bedrooms and two bathrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 62,
            },
        },
    ],
    'open_data_requirements': [],
    'unresolved_fields': [],
    'confirmed_at': '2026-09-20T00:00:00+00:00',
}


request_4: RequirementRequest = {
    'request_id': 'request-bishan_hdb_buy',
    'schema_version': '0.3-draft',
    'conversation_id': 'thread-bishan_hdb_buy',
    'profile_id': 'profile-bishan_hdb_buy',
    'profile_version': 1,
    'intent': 'buy',
    'user_context': [],
    'listing_constraints': [
        {
            'constraint_id': 'bishan_hdb_buy-c1',
            'field_path': 'transaction_type',
            'operator': 'eq',
            'value': 'sale',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'bishan_hdb_buy-c2',
            'field_path': 'price.amount',
            'operator': 'lte',
            'value': 1000000,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'bishan_hdb_buy-c3',
            'field_path': 'price.currency',
            'operator': 'eq',
            'value': 'SGD',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'bishan_hdb_buy-c4',
            'field_path': 'price.period',
            'operator': 'eq',
            'value': 'total',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'bishan_hdb_buy-c5',
            'field_path': 'attributes.property_type',
            'operator': 'eq',
            'value': 'hdb',
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'bishan_hdb_buy-c6',
            'field_path': 'bedrooms',
            'operator': 'gte',
            'value': 3,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
        {
            'constraint_id': 'bishan_hdb_buy-c7',
            'field_path': 'attributes.area_sqft',
            'operator': 'gte',
            'value': 1000,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
    ],
    'derived_data_requirements': [
        {
            'requirement_id': 'bishan_hdb_buy-area',
            'category': 'accessibility',
            'target': 'Bishan',
            'metric': 'residential_area',
            'operator': 'eq',
            'value': True,
            'unit': None,
            'strength': 'hard',
            'priority': 'high',
            'source': {
                'message_id': 'msg-bishan_hdb_buy',
                'text': 'I want to buy an HDB flat in Bishan, with a total price not exceeding SGD 1000000, at least three bedrooms, and an area of at least 1000 square feet.',
                'start': 0,
                'end': 58,
            },
        },
    ],
    'open_data_requirements': [],
    'unresolved_fields': [],
    'confirmed_at': '2026-09-20T00:00:00+00:00',
}


#INPUTS = (request_1, request_2, request_3, request_4)
INPUTS = (request_1,)

async def run_all():
    for request in INPUTS:
        ctx = {
            "user_id": "live-check",
            "run_id": "run-" + request["request_id"],
            "conversation_id": request["conversation_id"],
            "attempt_id": None,
            "trace_id": "trace-" + request["request_id"],
            "call_id": "call-" + request["request_id"],
            "deadline_at": (datetime.now(timezone.utc) + timedelta(minutes=5)).isoformat(),
            "source_mode": "live",
        }
        print(request["request_id"], flush=True)
        result = await fulfill_requirements(request, ctx=ctx)
        print(json.dumps(result, ensure_ascii=False, indent=2), flush=True)


if __name__ == "__main__":
    asyncio.run(run_all())
